# Generated by Django 5.1.15 on 2026-03-17 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("price_alert", "Alerta de precio"),
                            ("new_promo", "Nueva promoción"),
                            ("shared_list_changed", "Lista compartida modificada"),
                            ("business_approved", "Negocio aprobado"),
                            ("business_rejected", "Negocio rechazado"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de notificación",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("body", models.TextField(verbose_name="Cuerpo")),
                ("is_read", models.BooleanField(default=False, verbose_name="Leída")),
                ("data", models.JSONField(default=dict, verbose_name="Datos adicionales")),
                (
                    "action_url",
                    models.CharField(
                        blank=True,
                        help_text="Deep link, p.ej. bargain://lists/42",
                        max_length=500,
                        verbose_name="URL de acción",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Soft delete — null significa no eliminada",
                        null=True,
                        verbose_name="Eliminada el",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserPushToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("token", models.CharField(max_length=200, verbose_name="Token Expo Push")),
                (
                    "device_id",
                    models.CharField(blank=True, max_length=200, verbose_name="ID de dispositivo"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token push de usuario",
                "verbose_name_plural": "Tokens push de usuario",
                "unique_together": {("user", "device_id")},
            },
        ),
    ]
