# Generated by Django 5.1.15 on 2026-03-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="data",
            field=models.JSONField(blank=True, default=dict, verbose_name="Datos adicionales"),
        ),
    ]
