# Generated by Django 5.1.15 on 2026-03-25 21:15

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopping_lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_location', django.contrib.gis.db.models.fields.PointField(help_text='Ubicacion del usuario al optimizar', srid=4326, verbose_name='Ubicacion del usuario')),
                ('max_distance_km', models.FloatField(default=10.0, verbose_name='Radio maximo (km)')),
                ('max_stops', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)], verbose_name='Numero maximo de paradas')),
                ('optimization_mode', models.CharField(choices=[('precio', 'Precio'), ('distancia', 'Distancia'), ('balanced', 'Equilibrado')], default='balanced', max_length=20, verbose_name='Modo de optimizacion')),
                ('w_precio', models.FloatField(default=0.5, verbose_name='Peso precio')),
                ('w_distancia', models.FloatField(default=0.3, verbose_name='Peso distancia')),
                ('w_tiempo', models.FloatField(default=0.2, verbose_name='Peso tiempo')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio total')),
                ('total_distance_km', models.FloatField(verbose_name='Distancia total (km)')),
                ('estimated_time_minutes', models.FloatField(verbose_name='Tiempo estimado (min)')),
                ('route_data', models.JSONField(help_text='Paradas ordenadas con detalle por tienda', verbose_name='Datos de ruta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimizations', to='shopping_lists.shoppinglist', verbose_name='Lista de la compra')),
            ],
            options={
                'verbose_name': 'Resultado de optimizacion',
                'verbose_name_plural': 'Resultados de optimizacion',
                'ordering': ['-created_at'],
            },
        ),
    ]
