# Generated by Django 5.1.15 on 2026-03-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="source",
            field=models.CharField(
                choices=[
                    ("scraping", "Scraping"),
                    ("crowdsourcing", "Crowdsourcing"),
                    ("api", "API oficial"),
                    ("business", "Portal PYME"),
                ],
                default="scraping",
                max_length=20,
                verbose_name="Fuente",
            ),
        ),
    ]
